#+OPTIONS: toc:t h:4 num:nil
#+PROPERTY: header-args :results silent
* Usage
Given the modular structure of this conf, you may take just those
parts that are of interest to you.

In case you want to try it all, the simplest way is saving your
current configuration and cloning this repository in its place.
#+BEGIN_SRC sh
mv ~/.emacs.d ~/.emacs.d.bak
mv ~/.emacs ~/.emacs.bak
git clone --recursive https://github.com/jackjackk/emacs-conf.git ~/.emacs.d
#+END_SRC

Other strategies to merge an existing directory with a git repo can be found [[http://stackoverflow.com/questions/5377960/whats-the-best-practice-to-git-clone-into-an-existing-folder][here]]. In particular:
#+BEGIN_SRC sh
git clone https://github.com/jackjackk/emacs-conf.git ~/.emacs.d/.git --mirror --config core.bare=false
#+END_SRC
will transform your emacs conf dir in a working copy of this repository.
* The main file (~init.el~)
:PROPERTIES:
:tangle:   init.el
:END:

All conf code is self-contained in =~/.emacs.d= dir. If no =~/.emacs=
file is found, emacs will use =~/.emacs.d/init.el= (tangled from this file). This in
turn call other files in a modular fashion.

Make sure you *decomment just the packages you are interested in*,
otherwise be aware that all missing packages on repositories will be
downloaded and installed on startup, which requires time + internet
bandwidth.

Load the path with configuration files.
#+BEGIN_SRC elisp
(add-to-list 'load-path "~/.emacs.d/lisp")
#+END_SRC
** Customize built-in features
**** [[file:init-startup.org][Startup]]
#+BEGIN_SRC elisp
(load-library "init-startup.el")
#+END_SRC

**** [[file:init-general.org][General]]
#+BEGIN_SRC elisp
(load-library "init-general.el")
#+END_SRC

**** [[file:init-visual.org][Visual]]
#+BEGIN_SRC elisp
(load-library "init-visual.el")
#+END_SRC

**** [[file:init-text.org][Text]]
#+BEGIN_SRC elisp
(load-library "init-text.el")
#+END_SRC

**** [[file:init-os.org][OS integration]]
#+BEGIN_SRC elisp
(load-library "init-os.el")
#+END_SRC

**** [[file:init-latex.org][LaTeX]]
#+BEGIN_SRC elisp
(load-library "init-latex.el")
#+END_SRC

**** [[file:init-net.org][Network]]
#+BEGIN_SRC elisp
(load-library "init-net.el")
#+END_SRC

**** [[file:macros.el][Macros]]
#+BEGIN_SRC elisp
(load-library "macros.el")
#+END_SRC

**** +[[file:init-python.org][Python]]+
#+BEGIN_SRC elisp
;(load-library "init-python.el")
#+END_SRC
** Customize packages from repositories
#+BEGIN_SRC elisp
  (setq package-list '(
#+END_SRC

**** Text ([[file:init-mod-company.org][company]], [[file:init-mod-yasnippet.org][yasnippet]], [[file:init-mod-expand-region.org][expand-region]], [[file:init-mod-multiple-cursors.org][multiple-cursors]], [[file:init-mod-column-marker.org][column-marker]], +[[file:init-mod-bm.org][bm]]+)
#+BEGIN_SRC elisp
                       company
                       yasnippet
                       expand-region
                       multiple-cursors
                       column-marker
  ;                    bm
#+END_SRC

**** Navigation ([[file:init-mod-helm.org][helm]], [[file:init-mod-projectile.org][projectile]], [[file:init-mod-helm-projectile.org][helm-projectile]], [[file:init-mod-transpose-frame.org][transpose-frame]], +[[file:init-mod-neotree.org][neotree]]+)
#+BEGIN_SRC elisp
                       helm
                       projectile
                       helm-projectile
                       transpose-frame
  ;                    neotree
#+END_SRC

**** Org-mode ([[file:init-mod-org-plus-contrib.org][org-plus-contrib]], [[file:init-mod-ox-textile.org][ox-textile]], [[file:init-mod-ox-rst.org][ox-rst]]  [[file:init-mod-toc-org.org][toc-org]], [[file:init-mod-org-ref.org][org-ref]], [[file:init-mod-ox-pandoc.org][ox-pandoc]], +[[file:init-mod-org-redmine.org][org-redmine]]+, +[[file:init-mod-org-pomodoro.org][org-pomodoro]]+, +[[file:init-mod-org2blog.org][org2blog]]+)
#+BEGIN_SRC elisp
                       org-plus-contrib
                       ox-textile
                       ox-rst
                       toc-org
                       org-ref
                       ox-pandoc
  ;                    org-redmine
  ;                    org-pomodoro
  ;                    org2blog
#+END_SRC

**** LaTeX dev ([[file:init-mod-auctex.org][auctex]], [[file:init-mod-latex-preview-pane.org][latex-preview-pane]], [[file:init-mod-zotelo.org][zotelo]], [[file:init-mod-auctex-latexmk.org][auctex-latexmk]], [[file:init-mod-cdlatex.org][cdlatex]])
#+BEGIN_SRC elisp
                       auctex
                       latex-preview-pane
                       zotelo
                       auctex-latexmk
                       cdlatex
#+END_SRC

**** Tools ([[file:init-mod-magit.org][magit]], +[[file:init-mod-exec-path-from-shell.org][exec-path-from-shell]]+, +[[file:init-mod-eimp.org][eimp]]+, +[[file:init-mod-spray.org][spray]]+) 
#+BEGIN_SRC elisp
                       magit
  ;                    exec-path-from-shell
  ;                    eimp
  ;                    spray
#+END_SRC

**** Win dev ([[file:init-mod-powershell.org][powershell]])
#+BEGIN_SRC elisp
                       powershell
#+END_SRC
**** R dev ([[file:init-mod-ess.org][ess]], [[file:init-mod-markdown-mode.org][markdown-mode]], [[file:init-mod-polymode.org][polymode]])
#+BEGIN_SRC elisp
                       ess
                       markdown-mode
                       polymode
#+END_SRC

**** +Python dev+ ([[file:init-mod-elpy.org][elpy]], [[file:init-mod-anaconda-mode.org][anaconda-mode]], [[file:init-mod-company-anaconda.org][company-anaconda]], [[file:init-mod-websocket.org][websocket]] + [[file:init-mod-ein.org][ein]])
#+BEGIN_SRC elisp
  ;                    elpy
  ;                    anaconda-mode
  ;                    company-anaconda
  ;                    websocket
  ;                    ein
#+END_SRC

**** +Web dev+ ([[file:init-mod-simple-httpd.org][simple-httpd]], [[file:init-mod-js2-mode.org][js2-mode]], [[file:init-mod-skewer-mode.org][skewer-mode]])
#+BEGIN_SRC elisp
  ;                    simple-httpd
  ;                    js2-mode
  ;                    skewer-mode
#+END_SRC

**** +[[file:init-mod-android-mode.org][android-mode]]+
#+BEGIN_SRC elisp
   ;                    android-mode
#+END_SRC
** Customize packages from local subfolders
#+BEGIN_SRC elisp
  ))
  (setq other-package-list '(
#+END_SRC

**** [[file:init-mod-thing-edit.org][thing-edit]]
#+BEGIN_SRC elisp
                             thing-edit
#+END_SRC

**** [[file:init-mod-gams.org][gams]]
#+BEGIN_SRC elisp
                             gams
#+END_SRC


**** Org-mode ([[file:init-mod-ox-wk.org][ox-wk]], +[[file:init-mod-ob-gams.org][ob-gams]]+)
#+BEGIN_SRC elisp
                             ox-wk
  ;                          ob-gams
#+END_SRC

**** +[[file:init-mod-matlab.org][matlab]]+
#+BEGIN_SRC elisp
  ;                          matlab
#+END_SRC

**** +[[file:init-mod-speedread.org][speedread]]+
#+BEGIN_SRC elisp
  ;                          speedread
#+END_SRC

** Finish
#+BEGIN_SRC elisp
  ))
#+END_SRC

Call [[file:init-packages.org][init-packages]] to load modules defined above.
#+BEGIN_SRC elisp
  (load-library "init-packages.el")
#+END_SRC
* Useful references
- http://www.emacswiki.org/emacs/Reference_Sheet_by_Aaron_Hawley
- https://org-babel.readthedocs.io/en/latest/
* DISCLAIMER

THIS SOFTWARE IS PRIVIDED "AS IS" AND COMES WITH NO WARRANTY. USE AT YOUR OWN RISK. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OR CORRUPTION OF DATA). USE AT YOUR OWN RISK.
